#!/usr/bin/env bash
#use the if elif and else statement inside of loop
export i=1
while [ $i -le 10 ]
do 
    n="Best School"
    echo "$n"
    i=$(( i + 1))
    if [ $i -eq 4 ];
    then
       echo bad luck
       i=$(( i + 1 ))
    elif [ $i -eq 8 ];
  then 
     echo good luck
     i=$(( i + 1 ))
    fi
done
