#!/usr/bin/env bash
# File: 7-highlander
# Print "To infinity and beyond" indefinitely
# Print "I am invincible!!!" when receiving SIGTERM

# Trap SIGTERM
trap 'echo "I am invincible!!!"' SIGTERM

# Infinite loop
while true; do
    echo "To infinity and beyond"
    sleep 2
done
